### ISSUE TITLE
Understanding the demo

### ISSUE THREAD

**Issue by kohaugustine** [plotly/dash-drug-discovery-demo#8]
First off, I want to say thank you to the team for putting together this is really amazing demonstration of Dash applied to cheminformatics.

I just have a simple question about the app. What do the size of the circles mean?

**Comment by chriddyp** [comment]
Hey @kohaugustine , thanks! They represent molecule weight, same as the variable that's mapped to the `color` variable. You can see where this is done in the code here: https://github.com/plotly/dash-drug-discovery-demo/blob/master/app.py#L173-L174

**Comment by kohaugustine** [comment]
@chriddyp Thank you, this clarifies!
